#!/usr/bin/env python3
"""Executable controls for forward-only residual algebraogenesis.

The experiment has two deliberately separate parts.

1.  The beta_4 shift is generated by the noninvertible real map
        T_beta(x) = beta*x - floor(beta*x),
    where beta is the positive root of x^4-x-1.  Akiyama proved that this
    beta-shift is non-sofic.  We compute its reference expansion with exact
    algebraic sign tests and compare finite follower/Hankel growth with the
    sofic golden-mean shift.

2.  A computable scalar sequence q contains every finite word over every
    dyadic grid.  The closure of its tails is the Hilbert cube [0,1]^N.  The
    construction places an exact anti-identity Hankel minor of every order at
    a computable location, certifying unbounded linear predictive dimension.

No probabilistic assumption and no reverse transition are used.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from itertools import product
import json
import math
from typing import Iterable, Sequence


BitWord = tuple[int, ...]


def word_text(word: Sequence[int]) -> str:
    return "epsilon" if not word else "".join(str(bit) for bit in word)


@dataclass
class Beta4Oracle:
    """Exact arithmetic in Q(beta), beta^4=beta+1, at the positive root."""

    lo: Fraction = Fraction(1, 1)
    hi: Fraction = Fraction(5, 4)
    refinements: int = 0

    @staticmethod
    def minimal_polynomial(value: Fraction) -> Fraction:
        return value**4 - value - 1

    def refine_root(self) -> None:
        mid = (self.lo + self.hi) / 2
        if self.minimal_polynomial(mid) < 0:
            self.lo = mid
        else:
            self.hi = mid
        self.refinements += 1

    def polynomial_interval(
        self, coefficients: Sequence[int]
    ) -> tuple[Fraction, Fraction]:
        lower = Fraction(0)
        upper = Fraction(0)
        for degree, coefficient in enumerate(coefficients):
            if coefficient == 0:
                continue
            lo_power = self.lo**degree
            hi_power = self.hi**degree
            if coefficient > 0:
                lower += coefficient * lo_power
                upper += coefficient * hi_power
            else:
                lower += coefficient * hi_power
                upper += coefficient * lo_power
        return lower, upper

    def sign_at_beta(self, coefficients: Sequence[int]) -> int:
        """Return the certified sign of a degree-at-most-three polynomial."""

        if all(coefficient == 0 for coefficient in coefficients):
            return 0
        for _ in range(16384):
            lower, upper = self.polynomial_interval(coefficients)
            if lower > 0:
                return 1
            if upper < 0:
                return -1
            self.refine_root()
        raise RuntimeError("root isolation failed to certify an algebraic sign")

    @staticmethod
    def multiply_by_beta(coefficients: Sequence[int]) -> list[int]:
        a0, a1, a2, a3 = coefficients
        # beta*(a0+a1 beta+a2 beta^2+a3 beta^3), reduced by beta^4=beta+1.
        return [a3, a0 + a3, a1, a2]

    def greedy_expansion_of_one(self, count: int) -> BitWord:
        remainder = [1, 0, 0, 0]
        digits: list[int] = []
        for _ in range(count):
            next_remainder = self.multiply_by_beta(remainder)
            comparison = next_remainder.copy()
            comparison[0] -= 1
            digit = 1 if self.sign_at_beta(comparison) >= 0 else 0
            next_remainder[0] -= digit
            remainder = next_remainder
            digits.append(digit)
        return tuple(digits)

    def decimal_midpoint(self) -> float:
        return float((self.lo + self.hi) / 2)

    def refine_to_bits(self, bits: int) -> None:
        target_width = Fraction(1, 2**bits)
        while self.hi - self.lo > target_width:
            self.refine_root()


def admissible_beta_word(word: BitWord, reference: BitWord) -> bool:
    """Parry lexicographic test for a finite word against infinite d*_beta(1)."""

    if len(reference) < len(word):
        raise ValueError("reference expansion is too short")
    for start in range(len(word)):
        suffix = word[start:]
        if suffix > reference[: len(suffix)]:
            return False
    return True


def words_through_length(length: int) -> list[BitWord]:
    words: list[BitWord] = [()]
    for size in range(1, length + 1):
        words.extend(tuple(bits) for bits in product((0, 1), repeat=size))
    return words


def gf2_independent_indices(vectors: Iterable[int]) -> list[int]:
    """Greedily select linearly independent bit vectors over F_2."""

    basis: dict[int, int] = {}
    selected: list[int] = []
    for index, original in enumerate(vectors):
        value = original
        while value:
            pivot = value.bit_length() - 1
            if pivot not in basis:
                basis[pivot] = value
                selected.append(index)
                break
            value ^= basis[pivot]
    return selected


def hankel_certificate(reference: BitWord, depth: int) -> dict[str, object]:
    universe = words_through_length(depth)
    histories = [word for word in universe if admissible_beta_word(word, reference)]
    continuations = universe

    row_bits: list[int] = []
    for history in histories:
        bits = 0
        for column, continuation in enumerate(continuations):
            if admissible_beta_word(history + continuation, reference):
                bits |= 1 << column
        row_bits.append(bits)

    column_bits: list[int] = []
    for column in range(len(continuations)):
        bits = 0
        for row, encoded in enumerate(row_bits):
            if (encoded >> column) & 1:
                bits |= 1 << row
        column_bits.append(bits)

    selected_columns = gf2_independent_indices(column_bits)
    restricted_rows: list[int] = []
    for encoded in row_bits:
        restricted = 0
        for local_column, global_column in enumerate(selected_columns):
            if (encoded >> global_column) & 1:
                restricted |= 1 << local_column
        restricted_rows.append(restricted)
    selected_rows = gf2_independent_indices(restricted_rows)

    rank = len(selected_columns)
    if len(selected_rows) != rank:
        raise AssertionError("failed to recover a square full-rank minor")

    return {
        "depth": depth,
        "history_count": len(histories),
        "continuation_count": len(continuations),
        "gf2_rank": rank,
        "minor_histories": [word_text(histories[index]) for index in selected_rows],
        "minor_continuations": [
            word_text(continuations[index]) for index in selected_columns
        ],
    }


def residual_signature(
    history: BitWord, probes: Sequence[BitWord], reference: BitWord
) -> tuple[bool, ...]:
    return tuple(
        admissible_beta_word(history + continuation, reference)
        for continuation in probes
    )


def obstruction_guided_probe_growth(
    reference: BitWord, history_depth: int, oracle_depth: int
) -> dict[str, object]:
    histories = [reference[:length] for length in range(history_depth + 1)]
    oracle_probes = words_through_length(oracle_depth)
    oracle = [residual_signature(history, oracle_probes, reference) for history in histories]
    oracle_class_count = len(set(oracle))

    probes: list[BitWord] = [()]
    revisions: list[dict[str, object]] = []
    while True:
        visible: dict[tuple[bool, ...], list[int]] = {}
        for index, history in enumerate(histories):
            signature = residual_signature(history, probes, reference)
            visible.setdefault(signature, []).append(index)

        collision: tuple[int, int] | None = None
        for indices in visible.values():
            for left_offset, left in enumerate(indices):
                for right in indices[left_offset + 1 :]:
                    if oracle[left] != oracle[right]:
                        collision = (left, right)
                        break
                if collision:
                    break
            if collision:
                break

        if collision is None:
            break

        left, right = collision
        witness = next(
            continuation
            for continuation in oracle_probes
            if admissible_beta_word(histories[left] + continuation, reference)
            != admissible_beta_word(histories[right] + continuation, reference)
        )
        if witness in probes:
            raise AssertionError("obstruction engine proposed an existing probe")
        probes.append(witness)
        revisions.append(
            {
                "left_history": word_text(histories[left]),
                "right_history": word_text(histories[right]),
                "separating_continuation": word_text(witness),
            }
        )

    visible_class_count = len(
        {
            residual_signature(history, probes, reference) for history in histories
        }
    )
    if visible_class_count != oracle_class_count:
        raise AssertionError("probe refinement stopped before matching oracle classes")

    return {
        "history_depth": history_depth,
        "oracle_depth": oracle_depth,
        "oracle_residual_classes": oracle_class_count,
        "materialized_probes": len(probes),
        "revisions": revisions,
    }


def transport_defect_refinement(
    reference: BitWord, history_depth: int
) -> dict[str, object]:
    """Refine sampled histories toward a one-step derivative congruence.

    If histories u and w agree on every current probe v but ua and wa do not,
    the witness is some v already in the probe set and the required new
    observable is the transported probe av.  This is a finite sampled check,
    not a proof that the resulting quotient is globally transition-closed.
    """

    # Include inadmissible words so the rejecting/dead residual is represented.
    histories = words_through_length(history_depth)
    probes: list[BitWord] = [()]
    revisions: list[dict[str, object]] = []

    while True:
        visible: dict[tuple[bool, ...], list[int]] = {}
        for index, history in enumerate(histories):
            signature = residual_signature(history, probes, reference)
            visible.setdefault(signature, []).append(index)

        defect: tuple[int, int, int, BitWord] | None = None
        for indices in visible.values():
            for left_offset, left in enumerate(indices):
                for right in indices[left_offset + 1 :]:
                    for symbol in (0, 1):
                        left_after = residual_signature(
                            histories[left] + (symbol,), probes, reference
                        )
                        right_after = residual_signature(
                            histories[right] + (symbol,), probes, reference
                        )
                        if left_after != right_after:
                            witness = next(
                                probe
                                for probe, left_value, right_value in zip(
                                    probes, left_after, right_after
                                )
                                if left_value != right_value
                            )
                            defect = (left, right, symbol, witness)
                            break
                    if defect:
                        break
                if defect:
                    break
            if defect:
                break

        if defect is None:
            break

        left, right, symbol, witness = defect
        transported = (symbol,) + witness
        if transported in probes:
            raise AssertionError("transport defect did not generate a new probe")
        probes.append(transported)
        revisions.append(
            {
                "left_history": word_text(histories[left]),
                "right_history": word_text(histories[right]),
                "symbol": symbol,
                "old_probe": word_text(witness),
                "transported_probe": word_text(transported),
            }
        )

    visible_signatures = {
        residual_signature(history, probes, reference) for history in histories
    }
    successor_signatures = {
        residual_signature(history + (symbol,), probes, reference)
        for history in histories
        for symbol in (0, 1)
    }
    missing_successor_signatures = successor_signatures - visible_signatures
    if missing_successor_signatures:
        raise AssertionError("a sampled one-step target signature has no representative")

    return {
        "history_depth": history_depth,
        "history_count": len(histories),
        "sampled_residual_classes": len(visible_signatures),
        "materialized_probes": len(probes),
        "transport_defects_repaired": len(revisions),
        "dead_residual_included": True,
        "one_step_target_signatures_represented": not missing_successor_signatures,
        "scope": "sampled one-step congruence, not a global closed quotient",
        "revisions": revisions,
    }


def stage_size(stage: int) -> int:
    alphabet_size = 2**stage + 1
    return stage * alphabet_size**stage


def stage_offset(stage: int) -> int:
    return sum(stage_size(previous) for previous in range(1, stage))


def universal_q(index: int) -> Fraction:
    """Return q[index] without materializing any preceding block."""

    if index < 0:
        raise ValueError("index must be nonnegative")
    stage = 1
    remaining = index
    while remaining >= stage_size(stage):
        remaining -= stage_size(stage)
        stage += 1

    alphabet_size = 2**stage + 1
    word_index, coordinate = divmod(remaining, stage)
    place = stage - coordinate - 1
    digit_index = (word_index // alphabet_size**place) % alphabet_size
    return Fraction(digit_index, 2**stage)


def compile_dyadic_block(target: Sequence[Fraction], precision_bits: int) -> dict[str, object]:
    stage = max(len(target), precision_bits)
    denominator = 2**stage
    alphabet_size = denominator + 1

    digit_indices = []
    for value in target:
        scaled = value * denominator
        nearest = (scaled.numerator * 2 + scaled.denominator) // (2 * scaled.denominator)
        digit_indices.append(max(0, min(denominator, nearest)))
    digit_indices.extend([0] * (stage - len(digit_indices)))

    lexicographic_rank = 0
    for digit_index in digit_indices:
        lexicographic_rank = lexicographic_rank * alphabet_size + digit_index
    position = stage_offset(stage) + stage * lexicographic_rank
    observed = [universal_q(position + offset) for offset in range(len(target))]
    error = max(abs(left - right) for left, right in zip(target, observed))
    if error > Fraction(1, denominator * 2):
        raise AssertionError("dyadic block compiler exceeded nearest-grid error")

    return {
        "stage": stage,
        "position": position,
        "position_decimal_digits": len(str(position)),
        "target": [str(value) for value in target],
        "observed": [str(value) for value in observed],
        "max_error": str(error),
        "error_bound": str(Fraction(1, denominator * 2)),
    }


def compile_sparse_dyadic_cylinder(
    target: dict[int, Fraction], precision_bits: int
) -> dict[str, object]:
    """Compile constraints at arbitrary finite coordinate indices."""

    if not target or min(target) < 0:
        raise ValueError("target must use nonnegative coordinate indices")
    stage = max(max(target) + 1, precision_bits)
    denominator = 2**stage
    alphabet_size = denominator + 1
    digit_indices = [0] * stage
    for coordinate, value in target.items():
        scaled = value * denominator
        nearest = (scaled.numerator * 2 + scaled.denominator) // (2 * scaled.denominator)
        digit_indices[coordinate] = max(0, min(denominator, nearest))

    lexicographic_rank = 0
    for digit_index in digit_indices:
        lexicographic_rank = lexicographic_rank * alphabet_size + digit_index
    position = stage_offset(stage) + stage * lexicographic_rank
    observed = {
        coordinate: universal_q(position + coordinate) for coordinate in target
    }
    error = max(abs(target[index] - observed[index]) for index in target)
    if error > Fraction(1, denominator * 2):
        raise AssertionError("sparse cylinder compiler exceeded nearest-grid error")

    return {
        "stage": stage,
        "position": position,
        "position_decimal_digits": len(str(position)),
        "coordinates": sorted(target),
        "target": {str(index): str(target[index]) for index in sorted(target)},
        "observed": {str(index): str(observed[index]) for index in sorted(target)},
        "max_error": str(error),
        "error_bound": str(Fraction(1, denominator * 2)),
    }


def anti_identity_hankel_certificate(order: int) -> dict[str, object]:
    stage = 2 * order - 1
    alphabet_size = 2**stage + 1
    # The listed word is 0^(k-1),1,0^(k-1).  Value 1 has grid index 2^stage.
    lexicographic_rank = 2**stage * alphabet_size ** (order - 1)
    position = stage_offset(stage) + stage * lexicographic_rank
    matrix = [
        [universal_q(position + row + column) for column in range(order)]
        for row in range(order)
    ]
    expected = [
        [Fraction(int(row + column == order - 1), 1) for column in range(order)]
        for row in range(order)
    ]
    if matrix != expected:
        raise AssertionError("constructed Hankel block is not anti-identity")
    determinant = -1 if (order * (order - 1) // 2) % 2 else 1
    return {
        "order": order,
        "position": position,
        "position_decimal_digits": len(str(position)),
        "determinant": determinant,
    }


def main() -> None:
    beta = Beta4Oracle()
    maximum_hankel_depth = 10
    maximum_probe_total = 18 + 12
    reference_length = max(96, 2 * maximum_hankel_depth, maximum_probe_total)
    beta4_reference = beta.greedy_expansion_of_one(reference_length)
    beta.refine_to_bits(80)
    golden_reference = tuple((1, 0)[index % 2] for index in range(reference_length))

    beta_hankel = [
        hankel_certificate(beta4_reference, depth)
        for depth in range(1, maximum_hankel_depth + 1)
    ]
    golden_hankel = [
        hankel_certificate(golden_reference, depth)
        for depth in range(1, maximum_hankel_depth + 1)
    ]

    beta_refinement = obstruction_guided_probe_growth(beta4_reference, 18, 12)
    golden_refinement = obstruction_guided_probe_growth(golden_reference, 18, 12)
    beta_transport_refinement = transport_defect_refinement(beta4_reference, 8)
    golden_transport_refinement = transport_defect_refinement(golden_reference, 8)

    dense_block = compile_dyadic_block(
        [Fraction(13, 100), Fraction(71, 100), Fraction(11, 25), Fraction(23, 25)],
        precision_bits=8,
    )
    sparse_cylinder = compile_sparse_dyadic_cylinder(
        {2: Fraction(13, 100), 11: Fraction(71, 100)}, precision_bits=8
    )
    unbounded_minors = [anti_identity_hankel_certificate(order) for order in range(1, 9)]

    cylinder_tail_bounds = [
        {"coordinates": count, "uniform_tail_bound": str(Fraction(1, 2**count))}
        for count in (2, 4, 8, 16)
    ]

    report = {
        "beta4": {
            "minimal_polynomial": "x^4-x-1",
            "certified_root_interval": [str(beta.lo), str(beta.hi)],
            "root_midpoint": beta.decimal_midpoint(),
            "root_refinements": beta.refinements,
            "reference_prefix": word_text(beta4_reference[:64]),
            "forward_collision": "T_beta(0)=T_beta(1/beta)=0",
            "published_classification": "non-sofic (Akiyama)",
            "hankel_blocks": beta_hankel,
            "obstruction_guided_refinement": beta_refinement,
            "transport_defect_refinement": beta_transport_refinement,
        },
        "golden_mean_control": {
            "reference_prefix": word_text(golden_reference[:32]),
            "published_classification": "sofic",
            "hankel_blocks": golden_hankel,
            "obstruction_guided_refinement": golden_refinement,
            "transport_defect_refinement": golden_transport_refinement,
        },
        "computable_hilbert_residual": {
            "dense_block_compiler": dense_block,
            "sparse_cylinder_compiler": sparse_cylinder,
            "exact_hankel_minors": unbounded_minors,
            "cylinder_function_tail_control": cylinder_tail_bounds,
            "semantic_completion": "closure{shift^n(q)}=[0,1]^N",
            "transition": "one-sided forward shift",
        },
    }

    if [block["gf2_rank"] for block in beta_hankel] != [2, 2, 2, 2, 4, 6, 8, 8, 10, 10]:
        raise AssertionError("beta-4 Hankel rank regression")
    if [block["gf2_rank"] for block in golden_hankel] != [2] * 10:
        raise AssertionError("golden-mean Hankel rank regression")
    if (beta_refinement["oracle_residual_classes"], beta_refinement["materialized_probes"]) != (14, 14):
        raise AssertionError("beta-4 obstruction-guided refinement regression")
    if (golden_refinement["oracle_residual_classes"], golden_refinement["materialized_probes"]) != (2, 2):
        raise AssertionError("golden-mean obstruction-guided refinement regression")
    expected_transport_chain = ["1", "01", "001", "0001", "00001", "000001", "0000001"]
    if [revision["transported_probe"] for revision in beta_transport_refinement["revisions"]] != expected_transport_chain:
        raise AssertionError("beta-4 transported-probe chain regression")
    if (beta_transport_refinement["sampled_residual_classes"], beta_transport_refinement["transport_defects_repaired"]) != (9, 7):
        raise AssertionError("beta-4 sampled transport regression")
    if (golden_transport_refinement["sampled_residual_classes"], golden_transport_refinement["transport_defects_repaired"]) != (3, 1):
        raise AssertionError("golden-mean sampled transport regression")
    if dense_block["position"] != 19974216792258773014 or dense_block["max_error"] != "3/1600":
        raise AssertionError("dense dyadic compiler regression")
    if sparse_cylinder["coordinates"] != [2, 11] or sparse_cylinder["stage"] != 12:
        raise AssertionError("sparse dyadic cylinder regression")
    expected_determinants = [1, -1, -1, 1, 1, -1, -1, 1]
    if [certificate["determinant"] for certificate in unbounded_minors] != expected_determinants:
        raise AssertionError("anti-identity determinant regression")
    if unbounded_minors[-1]["position_decimal_digits"] != 61:
        raise AssertionError("order-eight Hankel position regression")

    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
